name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

      ## create application.properties
    - name: make application.properties
      run: |
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.PROPERTIES }}" > ./application.properties
      shell: bash

      ## create application-alpha.properties
    - name: make application-alpha.properties
      run: |
        cd ./src/main/resources
        touch ./application-alpha.properties
        echo "${{ secrets.ALPHA_PROPERTIES }}" > ./application-alpha.properties
      shell: bash

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Docker build
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker build -t mung-friend .
        docker tag mung-friend souliat/mung-friend:${GITHUB_SHA::7}
        docker push souliat/mung-friend:${GITHUB_SHA::7}

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ec2-3-39-6-175.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          docker pull redis
          docker run --name redis -d -p 6379:6379 redis --save 60 1 --loglevel warning
          docker pull souliat/mung-friend:${GITHUB_SHA::7}
          docker tag souliat/mung-friend:${GITHUB_SHA::7} mung-friend
          docker stop server
          docker run --rm --name server -p 80:8080 -e TZ=Asia/Seoul --link redis:redis -d mung-friend

